export const config = {
  developer: {
    name: "Shakith A",
    title: "Full Stack .NET Developer",
    subtitle: "C# Developer | ASP.NET MVC Developer | Java Developer",
    bio: "Aspiring Full Stack .NET Developer currently undergoing professional training at Faith Infotech. Building scalable web applications and exploring UI/UX Design, Video Editing, Content Creation, and Digital Marketing.",
    avatar: "https://ui-avatars.com/api/?name=Shakith+A&background=0a0a0a&color=fff&size=200",
    about: "Computer Science and Engineering student passionate about backend development, databases, frontend technologies, UI/UX design, and digital creativity. Interested in building practical software solutions and improving continuously.",
  },
  social: {
    github: "shaki-12",
    email: "shakith2004@gmail.com",
    linkedin: "shakith-a-0484a027b",
    location: "Chennai, Tamil Nadu, India",
  },
  experience: [
    {
      id: 1,
      company: "Faith Infotech",
      role: "Full Stack .NET Developer Trainee",
      period: "Feb 2026 – Present",
      skills: ["ASP.NET MVC", "C#", "SQL Server", "MVC Architecture", "Real-world applications"],
    },
    {
      id: 2,
      company: "Pumo Technovation",
      role: "Java Intern",
      period: "Jul 2025 – Sep 2025",
      skills: ["Core Java", "OOP", "Collections", "Exception Handling"],
    },
  ],
  education: [
    {
      id: 1,
      institution: "Aalim Muhammed Salegh College of Engineering",
      degree: "B.E. Computer Science and Engineering",
      period: "2022 – 2026",
      gpa: "CGPA: 8.0",
    },
  ],
  projects: [
    {
      id: 1,
      title: "SyntaxFlow Hospital Management System",
      description: "A full-featured Hospital Management System with Receptionist, Doctor, Pharmacy, and Lab modules. Handles patient management and appointment scheduling end-to-end.",
      image: "/projects/project-1.webp",
      technologies: ["ASP.NET MVC", "C#", "SQL Server", "HTML", "CSS", "JavaScript"],
      features: ["Receptionist Module", "Doctor Module", "Pharmacy Module", "Lab Module", "Patient Management", "Appointment Scheduling"],
      github: "https://github.com/shaki-12",
      demo: "#",
    },
    {
      id: 2,
      title: "Student Feedback Sentiment Analyzer",
      description: "A browser-based sentiment analysis tool for student feedback with real-time classification, dashboard visualization, and sentiment scoring.",
      image: "/projects/project-2.webp",
      technologies: ["HTML", "CSS", "JavaScript"],
      features: ["Dashboard Visualization", "Sentiment Classification", "Real-Time Analysis"],
      github: "https://github.com/shaki-12",
      demo: "#",
    },
    {
      id: 3,
      title: "Portfolio Website",
      description: "A personal developer portfolio website showcasing projects, skills, and experience with a modern, minimal design.",
      image: "/projects/project-3.webp",
      technologies: ["HTML", "CSS", "JavaScript"],
      features: ["Responsive Design", "Project Showcase", "Contact Form"],
      github: "https://github.com/shaki-12",
      demo: "#",
    },
  ],
  skills: [
    { name: "C#", icon: "csharp" },
    { name: "Java", icon: "java" },
    { name: "JavaScript", icon: "javascript" },
    { name: "Python", icon: "python" },
    { name: "SQL", icon: "sql" },
    { name: "HTML5", icon: "html" },
    { name: "CSS3", icon: "css" },
    { name: "ASP.NET MVC", icon: "dotnet" },
    { name: "SQL Server", icon: "sqlserver" },
    { name: "MySQL", icon: "mysql" },
    { name: "Git", icon: "git" },
    { name: "Figma", icon: "figma" },
  ],
  skillCategories: [
    { category: "Programming Languages", items: ["C#", "Java", "JavaScript", "Python", "SQL"] },
    { category: "Frontend", items: ["HTML5", "CSS3", "JavaScript", "Responsive Design"] },
    { category: "Backend", items: ["ASP.NET MVC", "C#", "REST APIs"] },
    { category: "Database", items: ["SQL Server", "MySQL"] },
    { category: "Tools", items: ["Visual Studio", "VS Code", "Git", "GitHub", "Postman"] },
    { category: "Concepts", items: ["OOP", "MVC Architecture", "CRUD Operations", "Data Structures", "REST APIs"] },
    { category: "UI/UX", items: ["Figma", "Wireframing", "Prototyping", "User Interface Design"] },
    { category: "Creative", items: ["Video Editing", "Content Creation", "Motion Graphics Basics"] },
    { category: "Digital Marketing", items: ["Social Media Marketing", "SEO Fundamentals", "Content Marketing", "Branding"] },
  ],
};
